version: '3'
services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: database_name
      MYSQL_USER: database_user
      MYSQL_PASSWORD: database_password
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./installers/data/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  nginx:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx-config.conf:/etc/nginx/conf.d/default.conf
      - ./app_files:/var/www/html 

  php:
    build:
      context: ./
      dockerfile: Dockerfile  
    image: php:8.0-fpm
    volumes:
      - ./app_files:/var/www/html  # Update the volume mapping here
    depends_on:
      - mariadb

volumes:
  mariadb_data:
